### ISSUE TITLE
Browser Issues

### ISSUE THREAD

**Issue by JSmith92** [inkdlab/inkd-cyoa#13]
Only works on safari. Other browsers like chrome and firefox have issues. I noticed that Fiorefox almost works well. It just has problems loading audio.

**Comment by tiagodcosta** [comment]
The same issue here. Doesn't work on Chrome 56.0 (MacOS) or Firefox 51.0.1 (MacOS). It seems that some tag is not closed. 
![screencapture-localhost-3000-my-cyoa-html-1487012339865](https://cloud.githubusercontent.com/assets/19278068/22898340/f011a25a-f1f4-11e6-9de8-8b7f8f26152b.png)
