### ISSUE TITLE
Can we get volume controls on audio?

### ISSUE THREAD

**Issue by JSmith92** [inkdlab/inkd-cyoa#25]

**Comment by aarthyadityan** [comment]
Yes, it is supported by the native HTML <audio> element:
https://www.w3schools.com/html/html5_audio.asp

You can just add 'controls' to the audio tag, e.g., <audio is = "inkd-audio" name = "violin" controls>

If we want a master volume control for all the audio elements used in a cyoa, I can look into adding that feature in Polymer

**Comment by JSmith92** [comment]
Thats good too. Sorry I meant setting the pitch of a sound/audio. Some sounds come out a lot louder than others. Can set how loud a sound would be in the code? I remember I could do something like this in .js but not sure about .html.

**Comment by aarthyadityan** [comment]
Ah, okay.  This seems to work in Safari:
`<audio is = "inkd-audio" name = "violin" volume = "0.5">`

We would have to test browser support for it.

**Comment by JSmith92** [comment]
Ok great, thanks. I will test it.

**Comment by JSmith92** [comment]
Not hearing a difference in with that code on Safari or Chrome..

**Comment by aarthyadityan** [comment]
Interesting, worked for me in Safari 10.0.3. 
I just updated the 'inkd-audio' file on Github. Can you check if it works on your browsers?

**Comment by JSmith92** [comment]
The lab's Safari is on 9.0.2. I'll try your update.

**Comment by JSmith92** [comment]
Now I'm getting no audio with the new updated <inkd-audio>

**Comment by aarthyadityan** [comment]
Oh, oops! I will be at the lab in about an hour. I'll troubleshoot then

**Comment by JSmith92** [comment]
Ok no problem
